"""empty message

Revision ID: 1e577e0b29ff
Revises: b57d382bba46
Create Date: 2024-03-01 11:06:30.369856

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1e577e0b29ff'
down_revision = 'b57d382bba46'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('gender')
        batch_op.drop_column('phone')
        batch_op.drop_column('address')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('address', sa.VARCHAR(length=250), nullable=True))
        batch_op.add_column(sa.Column('phone', sa.VARCHAR(length=50), nullable=True))
        batch_op.add_column(sa.Column('gender', sa.VARCHAR(length=50), nullable=True))

    # ### end Alembic commands ###
